-- AlterTable
ALTER TABLE "RFQ" ADD COLUMN "tokenType" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RFQ" ADD COLUMN "pricingMode" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RFQ" ADD COLUMN "auctionSource" TEXT;
ALTER TABLE "RFQ" ADD COLUMN "winnerAccepted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RFQ" ADD COLUMN "paid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RFQ" ADD COLUMN "receiptHash" TEXT;
